### ISSUE TITLE
Sql Logging using own stored procedure and table

### ISSUE THREAD

**Issue by martinconvero** [sgryphon/essential-diagnostics#29]
I installed your nuget package Essential.Diagnostics.SqlDatabaseTraceListener but that did not include the diagnostics_regsql.exe for creating the sql stuff. So I tried using my own stored procedure and table but there is no documentation on how to implement this. Can someone please show me how to do this?

**Comment by sgryphon** [comment]
The tool is in the packages directory: packages\Essential.Diagnostics.SqlDatabaseTraceListener.2.0.206\tools

As well as the .EXE, the SQL files are there as well, if you want to run them directly.

The SQL files can also be downloaded directly from the source code here on Git: https://github.com/sgryphon/essential-diagnostics/tree/develop/src/Essential.Diagnostics.RegSql

I will keep this item open to make the instructions clearer on installation about where to find the tool, etc.

**Comment by sgryphon** [comment]
Detailed directory information added to readme (displayed when package is installed)
